apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-app-api-ingress
spec:
  ingressClassName: nginx
  type: ClusterIP
  rules:
  - host: {{ cookiecutter.project_domain }}
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: test-app-api
            port:
              number: 80
      - path: /admin/
        pathType: Prefix
        backend:
          service:
            name: test-app-api
            port:
              number: 80
