apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{cookiecutter.api_slug}}-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{cookiecutter.api_slug}}-api
  minReplicas: 1
  maxReplicas: 100
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 100
          periodSeconds: 10
    scaleUp:
      policies:
        - periodSeconds: 10
          type: Pods
          value: 100
      
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

