apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.api_slug}}-api
spec:
  type: ClusterIP
  selector:
    name: {{cookiecutter.api_slug}}-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
