apiVersion: v1
kind: Service
metadata:
    name: {{cookiecutter.angular_slug}}-ui
spec:
    type: ClusterIP
    selector:
        name: {{cookiecutter.angular_slug}}-ui
    ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
